baseURL = "http://example.com/"
languageCode = "en-us"
title = "Kevin Ou's Website"
theme="PaperMod"

[menu]

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

  [[menu.main]]
  name = "Resume"
  url = "/resume/"
  weight = 2

  [[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/kevin-ou-0ba3721b7/"
  weight = 3

  [[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 4



